// Original C++ AGG 2.6 port of the canvas_ity microbenchmark suite.
// The workloads, their RNG streams, scene geometry, and the timing
// methodology (best trial time on a fresh canvas, repeated) match
// bench/microbench.cpp. Rendering-model differences are listed below.
//
// API-mapping notes and caveats:
// - AGG 2.6 is immediate-mode like canvas_ity, so most workloads map
//   one-to-one. Full circles use the same 16 cubic segments generated by
//   canvas_ity's arc implementation.
// - gradient_linear/radial use AGG's span gradients (span_gradient +
//   gradient_linear/gradient_radial + span_interpolator_linear).  AGG
//   blends in 8-bit sRGB without canvas_ity's gamma linearization. Its
//   focused-radial model also cannot represent a nonzero start radius.
// - composite_ops maps the eleven canvas operations onto AGG's
//   comp_op_rgba_* set through pixfmt_custom_blend_rgba.
// - pattern_tiled, image_scaled, clip_heavy (rect clipping only), and
//   shadow_blurred are omitted (no equivalents; image span filters
//   exist but are a separate pipeline).
// - The fill rule is nonzero, matching canvas_ity's default.
//
//   clang++ -O2 -I<agg>/include -o microbench_agg26 \
//       microbench_agg26.cpp <agg>/src/*.cpp
//
//   ./microbench_agg26 [trials]

#include <agg_rendering_buffer.h>
#include <agg_pixfmt_rgba.h>
#include <agg_rasterizer_scanline_aa.h>
#include <agg_renderer_scanline.h>
#include <agg_scanline_u.h>
#include <agg_path_storage.h>
#include <agg_conv_curve.h>
#include <agg_conv_stroke.h>
#include <agg_conv_transform.h>
#include <agg_trans_affine.h>
#include <agg_span_gradient.h>
#include <agg_span_allocator.h>
#include <agg_span_interpolator_linear.h>
#include <vector>

#if defined( __linux__ )
#include <time.h>
#elif defined( _WIN32 )
#include <windows.h>
#elif defined( __MACH__ )
#include <mach/mach_time.h>
#else
#include <sys/time.h>
#endif
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>

static double get_seconds()
{
#if defined( __linux__ )
    timespec now;
    clock_gettime( CLOCK_MONOTONIC, &now );
    return now.tv_sec + now.tv_nsec * 1.0e-9;
#elif defined( _WIN32 )
    static double rate = 0.0;
    if ( !rate )
    {
        LARGE_INTEGER frequency;
        QueryPerformanceFrequency( &frequency );
        rate = 1.0 / static_cast< double >( frequency.QuadPart );
    }
    LARGE_INTEGER now;
    QueryPerformanceCounter( &now );
    return now.QuadPart * rate;
#elif defined( __MACH__ )
    static mach_timebase_info_data_t frequency;
    mach_timebase_info( &frequency );
    return mach_absolute_time() * frequency.numer * 1.0e-9 /
           frequency.denom;
#else
    timeval now;
    gettimeofday( &now, 0 );
    return now.tv_sec + now.tv_usec * 1.0e-6;
#endif
}

static unsigned long long rng_state = 0x243f6a8885a308d3ULL;
static float frand()
{
    rng_state ^= rng_state << 13;
    rng_state ^= rng_state >> 7;
    rng_state ^= rng_state << 17;
    return static_cast< float >( rng_state & 0xffffffULL ) /
           static_cast< float >( 0x1000000ULL );
}
// A comp-op-aware blender for the composite-ops workload.
struct blender_comp_op_rgba
    : agg::comp_op_adaptor_rgba_pre<agg::rgba8, agg::order_rgba> {};

typedef agg::pixfmt_custom_blend_rgba<blender_comp_op_rgba,
    agg::rendering_buffer> pixfmt_comp_op;

typedef void ( *workload )( agg::rasterizer_scanline_aa<> &ras,
                            agg::scanline_u8 &sl,
                            agg::rendering_buffer &rbuf, int, int );

struct entry { char const *name; workload call; int width; int height; };

// Helpers -------------------------------------------------------------------

static void circle( agg::path_storage &path, float cx, float cy,
                    float radius )
{
    static float const tau = 6.28318531f;
    static int const steps = 16;
    float segment = tau / static_cast< float >( steps );
    float alpha = 4.0f / 3.0f * tanf( 0.25f * segment );
    float x1 = radius;
    float y1 = 0.0f;
    path.move_to( cx + x1, cy + y1 );
    for ( int step = 0; step < steps; ++step )
    {
        float angle = static_cast< float >( step + 1 ) * segment;
        float x2 = radius * cosf( angle );
        float y2 = radius * sinf( angle );
        path.curve4( cx + x1 - alpha * y1, cy + y1 + alpha * x1,
                     cx + x2 + alpha * y2, cy + y2 - alpha * x2,
                     cx + x2, cy + y2 );
        x1 = x2;
        y1 = y2;
    }
    path.close_polygon();
}

static agg::rgba8 color8( float r, float g, float b, float a )
{
    return agg::rgba8( static_cast< unsigned char >( r * 255.0f + 0.5f ),
                       static_cast< unsigned char >( g * 255.0f + 0.5f ),
                       static_cast< unsigned char >( b * 255.0f + 0.5f ),
                       static_cast< unsigned char >( a * 255.0f + 0.5f ) );
}

struct gradient_three_color
{
    typedef agg::rgba8 color_type;
    color_type colors[ 256 ];

    gradient_three_color( color_type first, color_type middle,
                          color_type last, double middle_offset )
    {
        for ( unsigned index = 0; index < 256; ++index )
        {
            double offset = static_cast< double >( index ) / 255.0;
            colors[ index ] = offset <= middle_offset ?
                first.gradient( middle, offset / middle_offset ) :
                middle.gradient( last, ( offset - middle_offset ) /
                    ( 1.0 - middle_offset ) );
        }
    }

    unsigned size() const { return 256; }
    color_type operator[]( unsigned index ) const { return colors[ index ]; }
};

static void prepare_curve( agg::conv_curve<agg::path_storage> &curve,
                           double width )
{
    curve.approximation_scale( 4.0 );
    if ( width > 0.0 )
    {
        double ratio = 0.125 / std::max( 0.5 * width, 0.125 );
        double cosine = ( ratio - 2.0 ) * ratio * 2.0 + 1.0;
        curve.angle_tolerance( std::acos( cosine ) );
    }
}

// Workloads -----------------------------------------------------------------

static void path_construction( agg::rasterizer_scanline_aa<> &,
                               agg::scanline_u8 &,
                               agg::rendering_buffer &, int, int )
{
    agg::path_storage path;
    for ( int repeat = 0; repeat < 200; ++repeat )
    {
        path.remove_all();
        for ( int subpath = 0; subpath < 50; ++subpath )
        {
            path.move_to( frand() * 512.0, frand() * 512.0 );
            for ( int step = 0; step < 10; ++step )
            {
                path.line_to( frand() * 512.0, frand() * 512.0 );
                path.curve4( frand() * 512.0, frand() * 512.0,
                             frand() * 512.0, frand() * 512.0,
                             frand() * 512.0, frand() * 512.0 );
            }
        }
    }
}

static void flattening_fill( agg::rasterizer_scanline_aa<> &ras,
                             agg::scanline_u8 &sl,
                             agg::rendering_buffer &rbuf, int width,
                             int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    agg::path_storage path;
    for ( int subpath = 0; subpath < 60; ++subpath )
    {
        path.move_to( frand() * width, frand() * height );
        for ( int step = 0; step < 12; ++step )
            path.curve4( frand() * width, frand() * height,
                         frand() * width, frand() * height,
                         frand() * width, frand() * height );
        path.close_polygon();
    }
    agg::conv_curve<agg::path_storage> curve( path );
    prepare_curve( curve, 0.0 );
    ras.add_path( curve );
    agg::render_scanlines_aa_solid( ras, sl, base,
                                    color8( 0.2f, 0.4f, 0.8f, 1.0f ) );
}

static void fill_small( agg::rasterizer_scanline_aa<> &ras,
                        agg::scanline_u8 &sl,
                        agg::rendering_buffer &rbuf, int width,
                        int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    for ( int step = 0; step < 2000; ++step )
    {
        float x = frand() * width;
        float y = frand() * height;
        float radius = 2.0f + frand() * 6.0f;
        agg::path_storage path;
        circle( path, x, y, radius );
        agg::conv_curve<agg::path_storage> curve( path );
        prepare_curve( curve, 0.0 );
        ras.add_path( curve );
        agg::render_scanlines_aa_solid( ras, sl, base,
                                        color8( 0.2f, 0.4f, 0.8f, 1.0f ) );
    }
}

static void fill_large( agg::rasterizer_scanline_aa<> &ras,
                        agg::scanline_u8 &sl,
                        agg::rendering_buffer &rbuf, int width,
                        int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    for ( int step = 0; step < 20; ++step )
    {
        agg::path_storage path;
        path.move_to( -10.0, -10.0 );
        path.line_to( width + 20.0, -10.0 );
        path.line_to( width + 20.0, height + 20.0 );
        path.line_to( -10.0, height + 20.0 );
        path.close_polygon();
        ras.add_path( path );
        agg::render_scanlines_aa_solid( ras, sl, base,
                                        color8( 0.2f, 0.4f, 0.8f, 1.0f ) );
    }
}

static void fill_zone_plate( agg::rasterizer_scanline_aa<> &ras,
                             agg::scanline_u8 &sl,
                             agg::rendering_buffer &rbuf, int width,
                             int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    for ( int ring = 0; ring < 90; ++ring )
    {
        float cx = 0.5f * width;
        float cy = 0.5f * height;
        float radius = 3.0f + 3.0f * ring;
        agg::path_storage path;
        circle( path, cx, cy, radius );
        agg::conv_curve<agg::path_storage> curve( path );
        prepare_curve( curve, 0.0 );
        ras.add_path( curve );
        agg::render_scanlines_aa_solid( ras, sl, base,
                                        color8( 0.2f, 0.4f, 0.8f, 1.0f ) );
    }
}

static void stroke_many( agg::rasterizer_scanline_aa<> &ras,
                         agg::scanline_u8 &sl,
                         agg::rendering_buffer &rbuf, int width,
                         int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    agg::path_storage path;
    for ( int step = 0; step < 400; ++step )
    {
        path.move_to( frand() * width, frand() * height );
        path.curve4( frand() * width, frand() * height,
                     frand() * width, frand() * height,
                     frand() * width, frand() * height );
    }
    agg::conv_curve<agg::path_storage> curve( path );
    prepare_curve( curve, 1.5 );
    agg::conv_stroke<agg::conv_curve<agg::path_storage> > stroke( curve );
    stroke.width( 1.5 );
    ras.add_path( stroke );
    agg::render_scanlines_aa_solid( ras, sl, base,
                                    color8( 0.2f, 0.4f, 0.8f, 1.0f ) );
}

static void stroke_wide( agg::rasterizer_scanline_aa<> &ras,
                         agg::scanline_u8 &sl,
                         agg::rendering_buffer &rbuf, int width,
                         int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    agg::path_storage path;
    for ( int step = 0; step < 100; ++step )
    {
        path.move_to( frand() * width, frand() * height );
        for ( int part = 0; part < 6; ++part )
            path.curve4( frand() * width, frand() * height,
                         frand() * width, frand() * height,
                         frand() * width, frand() * height );
    }
    agg::conv_curve<agg::path_storage> curve( path );
    prepare_curve( curve, 12.0 );
    agg::conv_stroke<agg::conv_curve<agg::path_storage> > stroke( curve );
    stroke.width( 12.0 );
    stroke.line_join( agg::round_join );
    ras.add_path( stroke );
    agg::render_scanlines_aa_solid( ras, sl, base,
                                    color8( 0.2f, 0.4f, 0.8f, 1.0f ) );
}

static void gradient_linear( agg::rasterizer_scanline_aa<> &ras,
                             agg::scanline_u8 &sl,
                             agg::rendering_buffer &rbuf, int width,
                             int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    static const agg::rgba8 colors[ 3 ] = {
        color8( 1.0f, 0.2f, 0.1f, 1.0f ),
        color8( 0.1f, 0.9f, 0.3f, 1.0f ),
        color8( 0.2f, 0.1f, 1.0f, 1.0f ) };
    for ( int step = 0; step < 10; ++step )
    {
        agg::path_storage path;
        path.move_to( 0.0, 0.0 );
        path.line_to( width, 0.0 );
        path.line_to( width, height );
        path.line_to( 0.0, height );
        path.close_polygon();
        ras.add_path( path );
        agg::span_allocator<agg::rgba8> alloc;
        // The linear gradient is AGG's gradient_x composed with the
        // affine map from screen coordinates onto the gradient axis
        // (0,0) to (width,height).
        float length = std::sqrt( static_cast< float >( width ) *
                                      static_cast< float >( width ) +
                                  static_cast< float >( height ) *
                                      static_cast< float >( height ) );
        float ux = width / length;
        float uy = height / length;
        agg::gradient_x grad;
        agg::trans_affine matrix( ux, -uy, uy, ux, 0.0, 0.0 );
        agg::span_interpolator_linear<agg::trans_affine> interpolator(
            matrix );
        gradient_three_color color_function(
            colors[ 0 ], colors[ 1 ], colors[ 2 ], 0.5 );
        agg::span_gradient<agg::rgba8,
                           agg::span_interpolator_linear<agg::trans_affine>,
                           agg::gradient_x,
                           gradient_three_color> span(
                               interpolator, grad, color_function,
                               0.0, length );
        agg::render_scanlines_aa( ras, sl, base, alloc, span );
    }
}

static void gradient_radial( agg::rasterizer_scanline_aa<> &ras,
                             agg::scanline_u8 &sl,
                             agg::rendering_buffer &rbuf, int width,
                             int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    static const agg::rgba8 colors[ 3 ] = {
        color8( 1.0f, 0.9f, 0.2f, 1.0f ),
        color8( 0.2f, 0.5f, 0.9f, 0.8f ),
        color8( 0.1f, 0.1f, 0.4f, 0.2f ) };
    for ( int step = 0; step < 10; ++step )
    {
        agg::path_storage path;
        path.move_to( 0.0, 0.0 );
        path.line_to( width, 0.0 );
        path.line_to( width, height );
        path.line_to( 0.0, height );
        path.close_polygon();
        ras.add_path( path );
        agg::span_allocator<agg::rgba8> alloc;
        // The focused radial gradient places its center at the origin
        // of gradient space, so the matrix subtracts the center and
        // the focal point is given relative to it.
        agg::gradient_radial_focus grad;
        grad.init( 0.6 * width, -0.2 * width, -0.1 * height );
        agg::trans_affine matrix( 1.0, 0.0, 0.0, 1.0,
                                  -0.5 * width, -0.5 * height );
        agg::span_interpolator_linear<agg::trans_affine> interpolator(
            matrix );
        gradient_three_color color_function(
            colors[ 0 ], colors[ 1 ], colors[ 2 ], 0.7 );
        agg::span_gradient<agg::rgba8,
                           agg::span_interpolator_linear<agg::trans_affine>,
                           agg::gradient_radial_focus,
                           gradient_three_color> span(
                               interpolator, grad, color_function,
                               0.0, 0.6 * width );
        agg::render_scanlines_aa( ras, sl, base, alloc, span );
    }
}

static void composite_ops( agg::rasterizer_scanline_aa<> &ras,
                           agg::scanline_u8 &sl,
                           agg::rendering_buffer &rbuf, int width,
                           int height )
{
    // The canvas_ity workload cycles composite operation values
    // 1..15 skipping 5, 6, 8, and 9; all eleven map onto AGG's
    // comp_op set.
    static const unsigned operations[] = {
        agg::comp_op_src_in,
        agg::comp_op_src,
        agg::comp_op_src_out,
        agg::comp_op_dst_in,
        agg::comp_op_dst_atop,
        agg::comp_op_plus,
        agg::comp_op_dst_over,
        agg::comp_op_dst_out,
        agg::comp_op_src_atop,
        agg::comp_op_src_over,
        agg::comp_op_xor,
    };
    for ( size_t op = 0;
          op < sizeof( operations ) / sizeof( operations[ 0 ] ); ++op )
    {
        pixfmt_comp_op pix( rbuf, operations[ op ] );
        agg::renderer_base<pixfmt_comp_op> base( pix );
        agg::path_storage path;
        path.move_to( 0.1 * width, 0.1 * height );
        path.line_to( 0.7 * width, 0.1 * height );
        path.line_to( 0.7 * width, 0.7 * height );
        path.line_to( 0.1 * width, 0.7 * height );
        path.close_polygon();
        ras.add_path( path );
        agg::render_scanlines_aa_solid( ras, sl, base,
                                        color8( 0.9f, 0.5f, 0.2f, 0.6f ) );
    }
}

static void transforms( agg::rasterizer_scanline_aa<> &ras,
                        agg::scanline_u8 &sl,
                        agg::rendering_buffer &rbuf, int width,
                        int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    for ( int step = 0; step < 112; ++step )
    {
        agg::trans_affine matrix;
        matrix *= agg::trans_affine_translation( -0.5 * width,
                                                  -0.5 * height );
        matrix *= agg::trans_affine_scaling( 1.0 + 0.01 * step, 0.9 );
        matrix *= agg::trans_affine_rotation( 0.1 * step );
        matrix *= agg::trans_affine_translation( 0.5 * width,
                                                  0.5 * height );
        agg::path_storage path;
        circle( path, 0.4f * width, 0.4f * height, 0.3f * width );
        agg::conv_transform<agg::path_storage> transformed( path, matrix );
        agg::conv_curve<agg::conv_transform<agg::path_storage> > curve(
            transformed );
        curve.approximation_scale( 4.0 );
        ras.add_path( curve );
        agg::render_scanlines_aa_solid( ras, sl, base,
                                        color8( 0.2f, 0.4f, 0.8f, 1.0f ) );
    }
}

static void many_primitives( agg::rasterizer_scanline_aa<> &ras,
                             agg::scanline_u8 &sl,
                             agg::rendering_buffer &rbuf, int width,
                             int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    // Canonical banded-ink scene: 4 frand() calls per primitive
    // (x, y, width, height); colors come from a fixed table.
    static float const ink[ 6 ][ 4 ] = {
        { 0.13f, 0.23f, 0.38f, 1.0f }, { 0.91f, 0.35f, 0.13f, 1.0f },
        { 0.87f, 0.62f, 0.13f, 1.0f }, { 0.13f, 0.55f, 0.55f, 1.0f },
        { 0.45f, 0.27f, 0.49f, 1.0f }, { 0.94f, 0.93f, 0.88f, 1.0f } };
    for ( int step = 0; step < 22000; ++step )
    {
        float x = frand() * width;
        float y = frand() * height;
        int band = ( ( int )( x * 0.05f + y * 0.03f ) % 6 + 6 ) % 6;
        float w = 1.0f + frand() * 8.0f;
        float h = 1.0f + frand() * 8.0f;
        agg::path_storage path;
        path.move_to( x, y );
        path.line_to( x + w, y );
        path.line_to( x + w, y + h );
        path.line_to( x, y + h );
        path.close_polygon();
        ras.add_path( path );
        agg::render_scanlines_aa_solid(
            ras, sl, base,
            color8( ink[ band ][ 0 ], ink[ band ][ 1 ],
                    ink[ band ][ 2 ], ink[ band ][ 3 ] ) );
    }
}

static void complex_scene( agg::rasterizer_scanline_aa<> &ras,
                           agg::scanline_u8 &sl,
                           agg::rendering_buffer &rbuf, int width,
                           int height )
{
    agg::pixfmt_rgba32 pix( rbuf );
    agg::renderer_base<agg::pixfmt_rgba32> base( pix );
    for ( int layer = 0; layer < 10; ++layer )
    {
        double translate_x = frand() * 0.2 * width;
        double translate_y = frand() * 0.2 * height;
        double angle = frand() * 6.28;
        agg::trans_affine matrix;
        matrix *= agg::trans_affine_rotation( angle );
        matrix *= agg::trans_affine_translation( translate_x, translate_y );
        bool gradient = layer % 3 == 0;
        agg::rgba8 fill_color;
        if ( !gradient )
            fill_color = color8( frand(), frand(), frand(), frand() );
        agg::path_storage path;
        for ( int subpath = 0; subpath < 12; ++subpath )
        {
            path.move_to( frand() * width, frand() * height );
            for ( int step = 0; step < 8; ++step )
                path.curve4( frand() * width, frand() * height,
                             frand() * width, frand() * height,
                             frand() * width, frand() * height );
            path.close_polygon();
        }
        agg::conv_transform<agg::path_storage> transformed( path, matrix );
        agg::conv_curve<agg::conv_transform<agg::path_storage> > curve(
            transformed );
        curve.approximation_scale( 4.0 );
        ras.add_path( curve );
        if ( gradient )
        {
            static const agg::rgba8 stops[ 2 ] = {
                color8( 1.0f, 0.0f, 0.0f, 0.9f ),
                color8( 0.0f, 0.0f, 1.0f, 0.5f ) };
            agg::span_allocator<agg::rgba8> alloc;
            agg::gradient_x grad;
            double gradient_x = 0.5 * width;
            double gradient_y = 0.5 * height;
            double gradient_length = std::sqrt(
                gradient_x * gradient_x + gradient_y * gradient_y );
            double ux = gradient_x / gradient_length;
            double uy = gradient_y / gradient_length;
            agg::trans_affine matrix2 = matrix;
            matrix2.invert();
            matrix2 *= agg::trans_affine( ux, -uy, uy, ux, 0.0, 0.0 );
            agg::span_interpolator_linear<agg::trans_affine> interpolator(
                matrix2 );
            agg::gradient_linear_color<agg::rgba8> color_function(
                stops[ 0 ], stops[ 1 ] );
            agg::span_gradient<agg::rgba8,
                agg::span_interpolator_linear<agg::trans_affine>,
                agg::gradient_x,
                agg::gradient_linear_color<agg::rgba8> > span(
                    interpolator, grad, color_function, 0.0, gradient_length );
            agg::render_scanlines_aa( ras, sl, base, alloc, span );
        }
        else
            agg::render_scanlines_aa_solid( ras, sl, base, fill_color );
        double stroke_width = 1.0 + frand() * 3.0;
        agg::conv_curve<agg::conv_transform<agg::path_storage> >
            stroke_curve( transformed );
        stroke_curve.approximation_scale( 4.0 );
        double ratio = 0.125 / std::max( 0.5 * stroke_width, 0.125 );
        stroke_curve.angle_tolerance( std::acos(
            ( ratio - 2.0 ) * ratio * 2.0 + 1.0 ) );
        agg::conv_stroke<agg::conv_curve<
            agg::conv_transform<agg::path_storage> > > stroke( stroke_curve );
        stroke.width( stroke_width );
        ras.reset();
        ras.add_path( stroke );
        agg::render_scanlines_aa_solid( ras, sl, base, color8(
            frand(), frand(), frand(), frand() ) );
    }
}

static entry const tests[] = {
    { "path_construction", path_construction, 512, 512 },
    { "flattening_fill", flattening_fill, 512, 512 },
    { "fill_small", fill_small, 512, 512 },
    { "fill_large", fill_large, 1024, 1024 },
    { "fill_zone_plate", fill_zone_plate, 512, 512 },
    { "stroke_many", stroke_many, 512, 512 },
    { "stroke_wide", stroke_wide, 512, 512 },
    { "gradient_linear", gradient_linear, 512, 512 },
    { "gradient_radial", gradient_radial, 512, 512 },
    { "pattern_tiled", 0, 512, 512 },
    { "image_scaled", 0, 512, 512 },
    { "clip_heavy", 0, 512, 512 },
    { "composite_ops", composite_ops, 512, 512 },
    { "shadow_blurred", 0, 512, 512 },
    { "transforms", transforms, 512, 512 },
    { "many_primitives", many_primitives, 512, 512 },
    { "complex_scene", complex_scene, 512, 512 },
};

int main( int argc, char **argv )
{
    setvbuf( stdout, nullptr, _IONBF, 0 );
    int trials = argc > 1 ? atoi( argv[ 1 ] ) : 15;
    bool audit = getenv( "RNG_AUDIT" ) != 0;
    const int warmups = 3;
    int count = sizeof( tests ) / sizeof( tests[ 0 ] );
    double geo = 0.0;
    int supported = 0;
    for ( int index = 0; index < count; ++index )
    {
        entry const &item = tests[ index ];
        if ( !item.call )
        {
            printf( "%-20s %9s\n", item.name, "n/a" );
            continue;
        }
        unsigned long long seed =
            0x243f6a8885a308d3ULL + index * 0x9e3779b97f4a7c15ULL;
        if ( audit )
        {
            rng_state = seed;
            std::vector< unsigned char > pixels(
                static_cast< size_t >( item.width ) * item.height * 4,
                0u );
            agg::rendering_buffer rbuf( &pixels.front(), item.width,
                                        item.height, item.width * 4 );
            agg::rasterizer_scanline_aa<> ras;
            agg::scanline_u8 sl;
            item.call( ras, sl, rbuf, item.width, item.height );
            printf( "AUDIT %-18s %016llx\n", item.name, rng_state );
            continue;
        }
        std::vector< double > times;
        times.reserve( trials );
        for ( int trial = -warmups; trial < trials; ++trial )
        {
            rng_state = seed;   // identical scene every trial
            std::vector< unsigned char > pixels(
                static_cast< size_t >( item.width ) * item.height * 4,
                0u );
            agg::rendering_buffer rbuf( &pixels.front(), item.width,
                                        item.height, item.width * 4 );
            agg::rasterizer_scanline_aa<> ras;
            agg::scanline_u8 sl;
            double start = get_seconds();
            item.call( ras, sl, rbuf, item.width, item.height );
            double end = get_seconds();
            if ( trial >= 0 )
                times.push_back( end - start );
        }
        std::sort( times.begin(), times.end() );
        geo += log( times.front() );
        ++supported;
        printf( "%-20s %9.3f %9.3f\n", item.name,
                times.front() * 1000.0,
                times[ times.size() / 2 ] * 1000.0 );
    }
    printf( "%-20s %9.3f\n", "geo mean",
            exp( geo / supported ) * 1000.0 );
    return 0;
}
